services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: subscriptions
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    #volumes:
    #  - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    environment:
      DATABASE_URL: "postgresql://dbuser:dbpass@db:5432/subscriptions"
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
